### ISSUE TITLE
Issues with runtime bundling in sitecore

### ISSUE THREAD

**Issue by Manohar5itagi** [GuitarRich/sitecore.react#11]
We are facing issue after enabling runtime bundling in sitecore..

"Script threw an exception: 'Components' is undefined"

i can see in Sitecore React JsxView.cs file RenderView method, "Components." is hard coded.
and in our Jsx file we dont have ReactComponent which starts with Componets.

We tried removing this hard coded "Components." from file. we are not getting this issue after that.

**Comment by GuitarRich** [comment]
Runtime bundling is not currently supported in the latest version.
