### ISSUE TITLE
The version used by this.React() in the example is 5.2.4 meaning the component does not support MVC 4

### ISSUE THREAD

**Issue by jezzipin** [GuitarRich/sitecore.react#12]
After following the example in the repository description I ran into errors with a conflicting system.web.mvc version. Should 'Controller' come from System.Web.Mvc (I would expect it would) and if so, are you sure it is safe to upgrade the Sitecore MVC version to 5

**Comment by GuitarRich** [comment]
It should come from `System.Web.Mvc` - what version of Sitecore are you on? AFAIK Sitecore 8.2+ should already be on Mvc 5.x so it should be safe.

**Comment by jezzipin** [comment]
I'm moved to using Sitecore jss so happy for this to be closed.
