### ISSUE TITLE
Error rendering controller

### ISSUE THREAD

**Issue by Beatusvir** [GuitarRich/sitecore.react#5]
Hey guys

I'm trying to get this working, after creating a React Controller Rendering and setting the jsx file / controller setting. I add the rendering to a page and I get this:
![image](https://user-images.githubusercontent.com/10576465/28041800-c2199d22-6598-11e7-8ac3-0dc1a7b1da2c.png)

The controller is just this, I guess the problem is from `PageTitle` rendering name; thats what I was doing following the [this](http://www.sitecorenutsbolts.net/2017/07/05/Sitecore-React-Getting-Started-Creating-Components/)
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sitecore.React.Mvc.Controllers;
using Sitecore.Feature.PageContent.Model;

namespace Sitecore.Feature.PageContent.Controllers
{

    public class PageContentController : Controller
    {
        // GET: PageContent
        public ActionResult PageTitle()
        {
            var viewModel = new PageTitleViewModel
            {
                Title = "Some title",
                Summary = "Summary for page"
            };
            return this.React("PageTitle", viewModel);
        }
    }
}
```

This is the sitecore rendering
![image](https://user-images.githubusercontent.com/10576465/28041921-2e0fbafc-6599-11e7-86f2-07fa39612d46.png)

**Comment by GuitarRich** [comment]
It looks like your controller has not been registered with the IoC container. If you are on 8.2+ you need to make sure that all controllers are registered with the container using a configurator class. See this post for more details on that: https://kamsar.net/index.php/2016/08/Dependency-Injection-in-Sitecore-8-2/

**Comment by Beatusvir** [comment]
Thanks for your quick reply @GuitarRich , I'm more a react guy than a sitecore guy, and Sitecore is huge!!, checking it

**Comment by GuitarRich** [comment]
@Beatusvir did you get this sorted?

**Comment by Beatusvir** [comment]
@GuitarRich hey Richard, I started fresh from a new Habitat instance to make sure I wasnt doing something weird and this error is gone. Still couldnt get the controller to render my react component. I'll post the new question soon.

PS: off topic, I'm from Venezuela, last few weeks were crazy here so I had to run to Panama for a few days to see how everything would come out and just got home, so I can resume work for a now at least

**Comment by Beatusvir** [comment]
Alright, I was able to try this again. 

I'm using a controller that's rendering a regular cshtml view on the same page. I just added a new ActionResult that's returning the jsx component. The component is currently just a text. I'm getting the same error
