### ISSUE TITLE
Sample not working with latest version

### ISSUE THREAD

**Issue by mknayak** [GuitarRich/sitecore.react#8]
The sample solution provided in readme is not working with latest version. 
Even if we specify "BundleType" to runtime it's still looking for server.min.js
I got 'Components' is undefined , error while loading the page. In debug i can see its reading the data, In jsxView renderview, its throwing error.

**Comment by GuitarRich** [comment]
The runtime BundleType is not currently supported. For v2 right now, you must use Webpack. Runtime is coming in a future release.
